// src/app/(portfolio)/projects/[name]/[branch]/page.tsx
import type { Metadata } from "next";
import ProjectDetailClient from "../ProjectDetailClient";

// Generate static routes during build time for all repositories and their branches
// export async function generateStaticParams() {
//   return generateProjectBranchStaticParams();
// }

// Metadata Generator
export async function generateMetadata({
  params,
}: {
  params: Promise<{ name: string; branch: string }>;
}): Promise<Metadata> {
  const { name, branch } = await params;
  const decodedBranch = decodeURIComponent(branch);
  return {
    title: `${name} (${decodedBranch}) | Projects`,
    description: `Details and README for the repository: ${name} on branch ${decodedBranch}`,
  };
}

// Dynamic route Server Component (Next.js 16)
export default async function ProjectDetailPage({
  params,
}: {
  params: Promise<{ name: string; branch: string }>;
}) {
  const { name, branch } = await params;
  const decodedBranch = decodeURIComponent(branch);

  return (
    <ProjectDetailClient repoName={name} activeBranchName={decodedBranch} />
  );
}

// qwik-app/src/routes/projects/[name]/[branch]/index.tsx
import { component$ } from "@builder.io/qwik";
import { useLocation } from "@builder.io/qwik-city";
import { QProjectDetailPage } from "../../../../components/react/qwik-project-detail";
import type { DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  const loc = useLocation();
  const repoName = loc.params.name;
  const activeBranchName = decodeURIComponent(loc.params.branch);

  return (
    <>
      <QProjectDetailPage repoName={repoName} activeBranchName={activeBranchName} />
    </>
  );
});

export const head: DocumentHead = ({ params }) => {
  const name = params.name;
  const decodedBranch = decodeURIComponent(params.branch);
  return {
    title: `${name} (${decodedBranch}) | Projects`,
    meta: [
      {
        name: "description",
        content: `Details and README for the repository: ${name} on branch ${decodedBranch}`,
      },
    ],
  };
};
