// qwik-app/src/routes/api/projects/index.ts
import { type RequestHandler } from "@builder.io/qwik-city";
import { fetchAllPortfolios } from "../../../nextjs/lib/github";

export const onGet: RequestHandler = async ({ json }) => {
  try {
    const data = await fetchAllPortfolios();
    json(200, data);
  } catch (error) {
    console.error("Error in projects API route:", error);
    json(500, { error: "Internal Server Error" });
  }
};

// app/projects/page.tsx
import { fetchAllPortfolios } from "@/lib/github";
import { FALLBACK_REPOS } from "@/data/fallbackRepos";
import ProjectsClient from "./ProjectsClient";

export const dynamic = "force-dynamic";

export default async function ProjectsPage() {
	let repos = [];
	let isFallback = false;

	try {
		repos = await fetchAllPortfolios();
	} catch (error) {
		console.error(
			"Failed to fetch GitHub repos on server, using static fallback:",
			error,
		);
		repos = FALLBACK_REPOS;
		isFallback = true;
	}

	return (
		<ProjectsClient initialRepos={repos} isInitiallyFallback={isFallback} />
	);
}
