// app/[locale]/projects/[name]/page.tsx
import { redirect } from "next/navigation";
import { getProjectDefaultBranch } from "@/lib/projects";

export default async function ProjectDetailPage({
  params,
}: {
  params: Promise<{ name: string }>;
}) {
  const { name } = await params;
  const defaultBranch = await getProjectDefaultBranch(name);
  redirect(`/projects/${name}/${encodeURIComponent(defaultBranch)}`);
}

// qwik-app/src/routes/projects/[name]/index.ts
import { type RequestHandler } from "@builder.io/qwik-city";
import { getProjectDefaultBranch } from "../../../nextjs/lib/projects";

export const onGet: RequestHandler = async ({ params, redirect }) => {
  const { name } = params;
  const defaultBranch = await getProjectDefaultBranch(name);
  throw redirect(302, `/projects/${name}/${encodeURIComponent(defaultBranch)}`);
};
